<a href="https://colab.research.google.com/github/CarolMartinezPerez/03MAIR-Algoritmos-de-Optimizacion-2019/blob/master/Seminario/Carolina_Martinez_Seminario.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Carolina Martínez</br>
Link:https://colab.research.google.com/drive/13L-KZCJEtynqQc5-aKnPlH1fNGfS8FfP </br>
SEMINARIO. Algoritmos de Optimización</br>
Problema 1. Organizar sesiones de doblaje </br>


DESCRIPCIÓN DEL PROBLEMA </br>
Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de grabación independientemente del número de tomas que se graben. No es posible grabar más de 6 tomas por día. </br>El objetivo es planificar las sesiones por día de manera que se gasto por los servicios de los actores de doblaje sea el menor posible. </br>Los datos son:</br>Número de actores:  10</br>Número de tomas  :   30</br>Actores/Tomas: </br>0 en caso contrario

> 1 indica que el actor participa en la toma</br>


> 0 en caso contrario





### Primeras sección de cuestiones teóricas
(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?

**Respuesta:** (30 * 30) ! =
undefined

¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones?.

**Respuesta:**  (30 * 6) ! =
undefined

(*) ¿Cual es la estructura de datos que mejor se adapta al problema? 

**Respuesta:** 

Partimos de un dataset con toda la información de entrada que divido en la siguiente estructura: 

Estructura de entrada matriz de Tomas $T_i$ (30 tomas) y actor representados por '1' y '0' $A_i$ (10 actores) para el reparto:

        rep = df.iloc[:30,:10] # Matriz de reparto

Recuperamos también el coste por toma: $C_i$ (30 valores)

        nActores = df.iloc[0:30,[11]]# Lista de número de actores por toma

Y recuperamos el total de tomas por actor como: $T_ai$ (10 valores)

        nTomas = nTomas[0:10]# Lista de número de tomas por actor

Para las soluciones iniciales determiné la siguiente estructura:

        solucion = np.zeros((30, 6)) # Matriz de ceros, dónde se incluirán los valores de las tomas asignadas a cada día  o fila


        dia = np.zeros((30,10)) # En la matriz día se representan con unos y ceros si el actor va ese día o no respectivamente

**Para aplicar el algoritmo de optimización de ramificación y poda, se aplicó también una estructura de costes, representada por la posición de fila y columna como toma y día respectivamente.**

        costes = ...

(*)¿Cual es la función objetivo? 

**Respuesta:** Minimizar el coste total, suma del coste de cada día por actores que acuden. Lo podemos representar de la siguiente forma y comprobar que es un problema lineal.
$$ x_1a_1+x_2a_2+...+x_{10}a_{10} = \sum_{i=1}^{n} x_ia_i $$ Siendo *n* el número de días que acude cada actor y *a* el coste de acudir cada actor. Como el coste es igual para todos, lo consideraremos igual a 1 y por tanto nos quedará:$$  \sum_{i=1}^{n=10} x_i $$

(*)¿Es un problema de maximización o minimización?

**Respuesta:** Es un problema de minimización

Diseña un algoritmo para resolver el problema por fuerza bruta  
**Respuesta:** Al abordar el problema, no he visto viable recorrer todas las posibilidades para obtener la mejor solución, y he puesto el esfuerzo en la optimización.


### Análisis y preparación de datos de entrada y del modelo

Lo primero que he generado para plantear el problema es una **Solución inicial** determinista de partida.

In [1]:
# En este caso recojo por comodidad los datos del drive para trabajar (lo adjunto también en el ZIP)
from google.colab import drive
drive.mount('/content/drive')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [6]:
import pandas as pd 
df=pd.read_csv('/content/drive/My Drive/doblaje.csv',skiprows= 1, index_col=0) 
# Limpiamos el dataframe
df = df.drop(df.index[30], axis='index')

display(df)

1     2     3     4     5  ...    8    9   10  Unnamed: 11  Total
Toma                                 ...                                   
1       1.0   1.0   1.0   1.0   1.0  ...  0.0  0.0  0.0          NaN    5.0
2       0.0   0.0   1.0   1.0   1.0  ...  0.0  0.0  0.0          NaN    3.0
3       0.0   1.0   0.0   0.0   1.0  ...  0.0  0.0  0.0          NaN    3.0
4       1.0   1.0   0.0   0.0   0.0  ...  1.0  0.0  0.0          NaN    4.0
5       0.0   1.0   0.0   1.0   0.0  ...  1.0  0.0  0.0          NaN    3.0
6       1.0   1.0   0.0   1.0   1.0  ...  0.0  0.0  0.0          NaN    4.0
7       1.0   1.0   0.0   1.0   1.0  ...  0.0  0.0  0.0          NaN    4.0
8       1.0   1.0   0.0   0.0   0.0  ...  0.0  0.0  0.0          NaN    3.0
9       1.0   1.0   0.0   1.0   0.0  ...  0.0  0.0  0.0          NaN    3.0
10      1.0   1.0   0.0   0.0   0.0  ...  0.0  1.0  0.0          NaN    4.0
11      1.0   1.0   1.0   0.0   1.0  ...  1.0  0.0  0.0          NaN    5.0
12      1.0   1.0   1.0   1.0   0.0  ...  0.0  0.0  0.0          NaN    5.0
13      1.0   0.0   0.0   1.0   1.0  ...  0.0  0.0  0.0          NaN    3.0
14      1.0   0.0   1.0   0.0   0.0  ...  0.0  0.0  0.0          NaN    3.0
15      1.0   1.0   0.0   0.0   0.0  ...  0.0  0.0  0.0          NaN    3.0
16      0.0   0.0   0.0   1.0   0.0  ...  0.0  0.0  1.0          NaN    2.0
17      1.0   0.0   1.0   0.0   0.0  ...  0.0  0.0  0.0          NaN    2.0
18      0.0   0.0   1.0   0.0   0.0  ...  0.0  0.0  0.0          NaN    2.0
19      1.0   0.0   1.0   0.0   0.0  ...  0.0  0.0  0.0          NaN    2.0
20      1.0   0.0   1.0   1.0   1.0  ...  0.0  0.0  0.0          NaN    4.0
21      0.0   0.0   0.0   0.0   0.0  ...  1.0  0.0  0.0          NaN    2.0
22      1.0   1.0   1.0   1.0   0.0  ...  0.0  0.0  0.0          NaN    4.0
23      1.0   0.0   1.0   0.0   0.0  ...  0.0  0.0  0.0          NaN    2.0
24      0.0   0.0   1.0   0.0   0.0  ...  0.0  0.0  0.0          NaN    2.0
25      1.0   1.0   0.0   1.0   0.0  ...  0.0  0.0  1.0          NaN    4.0
26      1.0   0.0   1.0   0.0   1.0  ...  0.0  1.0  0.0          NaN    4.0
27      0.0   0.0   0.0   1.0   1.0  ...  0.0  0.0  0.0          NaN    2.0
28      1.0   0.0   0.0   1.0   0.0  ...  0.0  0.0  0.0          NaN    2.0
29      1.0   0.0   0.0   0.0   1.0  ...  0.0  0.0  0.0          NaN    3.0
30      1.0   0.0   0.0   1.0   0.0  ...  0.0  0.0  0.0          NaN    2.0
TOTAL  22.0  14.0  13.0  15.0  11.0  ...  4.0  2.0  2.0          NaN    NaN

[31 rows x 12 columns]

In [11]:
# preparación de datos
#reparto = df.loc['1':'30']
rep = df.iloc[:30,:10] # Matriz de reparto 
nTomas = df.loc['TOTAL'] 
nTomas = nTomas[0:10] # Lista de número de tomas por actor
nActores = df.iloc[0:30,[11]] # Lista de número de actores por toma
reparto = rep.join(nActores)  # Matriz de reparto + nActores
#display(df)
display(reparto)
#display(nTomas)
#display(nActores)

1    2    3    4    5    6    7    8    9   10  Total
Toma                                                         
1     1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0    5.0
2     0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0    3.0
3     0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0    3.0
4     1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0    4.0
5     0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0    3.0
6     1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0    4.0
7     1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0    4.0
8     1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0    3.0
9     1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    3.0
10    1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0    4.0
11    1.0  1.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0    5.0
12    1.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0    5.0
13    1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0    3.0
14    1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0    3.0
15    1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0    3.0
16    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0    2.0
17    1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0
18    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0    2.0
19    1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0
20    1.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0    4.0
21    0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0    2.0
22    1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    4.0
23    1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0
24    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0    2.0
25    1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0    4.0
26    1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0    4.0
27    0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0    2.0
28    1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0
29    1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0    3.0
30    1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0

### SOLUCIÓN INICIAL SIN OPTIMIZACIÓN:
Consiste en generar una solución al reparto en el mínimo de días posibles, y teniendo en cuenta la coincidencia de tomas de los actores, pero aún sin considerar el reparto en más de 5 días.

In [0]:
# Usaremos numpy y la solucion como salida
import numpy as np
solucion = np.zeros((30, 6)) # Matriz de ceros, dónde se incluirán los valores de las tomas asignadas a cada día o fila


In [0]:
# Cálculo del coste de la solucion en matriz de " max dias" x "max tomas/dia"
def calculo_coste(reparto, solucion):
  gasto = 3
  toma = []
  dia = np.zeros((30,10)) # En la matriz día se representan con unos y ceros si el actor va ese día o no respectivamente
  #actores_dia = np.zeros(30) 

  A,B = solucion.shape

  for i in range(A): # día
    for j in range(B): # toma
     if solucion[i,j] == 0:
       print(dia)
       return gasto
     else:
       toma = (df.loc[str(int(solucion[i,j]))].values)
       for k in range(len(toma)-1): # actor
         if toma[k] > 0:
          dia[i,k] = 1
    print('Día ',i+1,' van ', np.sum(dia[i]),' actores') 
    gasto += np.sum(dia[i])
  print('Reparto por día: ', dia)
  return


In [14]:
# Solucion para buscar las tomas con mayor coincidencia de actores
def mejor_vecino(vector,df):
  toma = vector[0:10]
  nToma = 0 
  maximo = 0

  for row in df.itertuples():

    value = df.loc[row.Index].values  # Recoge valores de la fila
    comp = np.logical_and(toma, value[0:-1]) # Operación AND entre la toma de entrada y la fila
    new_comp = np.array([1 if e == True else 0 for e in comp]) # trasformo a 1 y 0 la salida de la operación AND

    if np.sum(new_comp) >= maximo:   # Comparo con el valor maximo para quedarme con la toma con más actores coincidentes
      maximo = np.sum(new_comp)
      nToma = row.Index

  #print('toma mas coincidente ', nToma, type(nToma))
  return(nToma)

mejor_vecino(reparto.values[2], reparto)

'3'

In [0]:
# Seleccion de tomas / día
def seleccion_tomas_dia(reparto, solucion):
  resto_reparto = reparto

  for i in range(len(reparto)): # = dia -- hasta 30 si no está vacío el df, entonces ya habré devuelto la matriz solución
    if len(resto_reparto) == 0:
      return(solucion)
    else:

     # Seleccion de toma
     max_row = resto_reparto['Total'].idxmax()  # Devuelve el índice de la fila con mayor número de actores
     toma_ref = resto_reparto.loc[max_row].values

     # Recorro el dataframe seleccionando 6 tomas (el de mayor número de actores y otros 5 con mayor coincidencia de actores)
     for j in range(6):
      solucion[i,j] = mejor_vecino(toma_ref, resto_reparto) # lo repetiré 5 veces
      #display(resto_reparto)
      resto_reparto = resto_reparto.drop([str(int(solucion[i,j]))], axis = 0) # borro la toma  

    #print(solucion[i,:])
  
  return(solucion)


In [214]:
# Solución inicial constante para el ejemplo dado:
SOL_1 = seleccion_tomas_dia(reparto, solucion)
DIA_1 = calculo_coste(reparto, sol)
print(type(SOL_1))
print('REPARTO DE TOMAS POR DÍA: \n', SOL_1)
print('GASTO ', DIA_1)# print actores/dia y coste total

Día  1  van  7.0  actores
Día  2  van  8.0  actores
Día  3  van  9.0  actores
Día  4  van  5.0  actores
Día  5  van  9.0  actores
[[1. 1. 1. 1. 1. 1. 0. 1. 0. 0.]
 [1. 1. 0. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0

Complejidad: $\Theta(n^2)$ y cúbica el cálculo de actores por día.

### Segunda sección de cuestiones:

(*)Diseña un algoritmo que mejore la complejidad del algoritmo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

Después de resolver la obtención de una primera solución, y entiendo la dificultad para acercarnos al mejor resultado, obtuve las siguientes conclusiones:

1.   Debía mejorar la función de cálculo del coste de la solución dada.
2.   Al revisar los posibles algoritmos para el caso, creo que veo que necesito es una **Solución inicial aleatoria** en lugar de la abordada.
> Primero pensé en el algoritmo de **ramificación y poda** como buena solución de partida. Al intentar abordarlo y buscar documentación, veo que el problema se puede tanto, resolver con dicha solución, buscando los actores con mayores tomas y rellenando las tomas diarias límite, como por soluciones no deterministas, en concreto aplicar un algoritmo **genético**.


Referencia: http://eio.usc.es/pub/mte/descargas/ProyectosFinMaster/Proyecto_759.pdf

En la información referenciada, se crea una Solución inicial determinista también inicialmente pero es una solución basada en en el actor con más tomas.

Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorio:


Los actores que participan en la película se van escogiendo de forma aleatoria y
añadiendo a una convocatoria, incluyendo todos los takes en los que participa en dicha
convocatoria. Todos los actores que participen en cada take que se vaya añadiendo a
una convocatoria se añaden también a dicha convocatoria. Se repite este proceso hasta
completar el número máximo de takes por jornada de trabajo, en cuyo caso se añadirán
los takes siguientes a un nuevo día de grabación

In [0]:
# Algoritmo de generación de soluciones aleatorias

def tomas_actor(reparto, actor, solucion):
  toma = '0'
  tomas_actor = reparto
  # Comprueba si quedan tomas del actor
  if ((reparto[reparto[str(actor)].isin([1])]).shape[0]>0):
    tomas_actor = reparto[reparto[str(actor)].isin([1])]
    # Revisa en la solución parcial si ya está añadida la toma antes de devolverla
    for row in tomas_actor.iloc[:,:10]:

      if row in solucion:
        tomas_actor = tomas_actor.drop([row],axis = 0) #si esa toma estaba en la solucion la elimino
        print('la toma ',row, 'ya estaba, se elimina de las posibles')

      toma =  tomas_actor['Total'].idxmax() # type str
    print('toma escogida: ', toma)
 
  else: #No quedan tomas de ese actor
    print('No quedan tomas de este actor')
    toma = reparto.index[0] # Devuelvo la que queda
 
  return toma # búsqueda aleatoria de las posibles tomas del actor

# Devuelve otro actor vecino de la toma indicada 
def actor_vecino(reparto, actor, toma):
  value = reparto.loc[str(int(toma))].values  # Recoge valores de la fila
  subset = reparto.drop([str(int(toma))], axis = 0) #Elimino la toma como posibilidad de reparto
  actor_vecino = '0'

  # Devuelvo algún actor de la toma que aún tenga sesiones !!
  
  value[(int(actor)-1)]=0 # Elimino la posibilidad de elegir el mismo actor 
  max_row = 0
  for i in range(len(value)-1):

    if (value[i] == 1):
      #Elijo toma del actor con mayor número de actores
      if subset[subset[str(i+1)].isin([1])].shape[0] > 0: 
        print('llega aquí')
        tomas_actor= subset[subset[str(i+1)].isin([1])] # tomas del actor i

        if (int(tomas_actor['Total'].idxmax()) > max_row): #Para la toma con más vecinos
          max_row = int(tomas_actor['Total'].idxmax())
          actor_vecino = i+1
          print('max_row: ',max_row, 'actor_vecino: ',actor_vecino)
  
  # Si no hay actor vecino con sesiones devuelve '0'

  return str(actor_vecino)


In [0]:
# Solución recursiva
def seleccion_tomas_dia_5(reparto, solucion, dia):
  resto_reparto = reparto
  actor = str(np.random.randint(1,10))
  print('Actor escogido para este día: ', actor)

  if (len(resto_reparto) == 0) or (actor == '0'):
    print('Condición STOP')
    return(solucion, resto_reparto)
  
  else: # Todas las tomas repartidas
    A,B = solucion.shape
    for limite in range(B):
      actor_pre = actor
      if ((resto_reparto[resto_reparto[str(actor)].isin([1])]).shape[0]<1): # si ya no existe toma en la que participe el actor
        if limite == 0:
          actor =  actor_vecino(reparto, actor, resto_reparto.index[0]) # actor de alguna toma que queda
        else:
          #print('solucion[dia,limite-1]: ' ,solucion[dia,limite-1])
          actor = actor_vecino(reparto, actor, solucion[dia,limite-1]) # otro actor de la última toma escogida 
        print('Cambio de actor: ',actor)
      
        if (actor == '0'):
          print('No encontró actor vecino con tomas')
          actor = actor_vecino(reparto, actor_pre, resto_reparto.index[0]) # actor de alguna toma que queda

      if len(resto_reparto > 0):
        # Seleccion de toma 
        #print('Para la posición: ',dia,limite)
        solucion[dia,limite] = tomas_actor(resto_reparto, actor, solucion) #Añado una toma del actor en solucion [tomas_dia]
        if solucion[dia,limite] != 0:
          print('TOMA: ',solucion[dia, limite])
          resto_reparto = resto_reparto.drop(str(int(solucion[dia,limite])), axis = 0) #Elimino la toma del resto del reparto pendiente
      
      #print('tomas de actor: ',resto_reparto[resto_reparto[str(actor)].isin([1])].shape[0], type(resto_reparto[resto_reparto[str(actor)].isin([1])].shape[0]))
      #print('Resto de tomas: ',len(resto_reparto))

    solucion, resto_reparto = seleccion_tomas_dia_5(resto_reparto, solucion, dia+1)

  return solucion, resto_reparto

In [86]:


solucion_2 = np.zeros((30, 6)) # Matriz de ceros, dónde se incluirán los valores de las tomas asignadas a cada día o fila
# Solución para el ejemplo dado:
sol_aleatoria, resto = seleccion_tomas_dia_5(reparto, solucion_2, 0)
DIA_2 = calculo_coste(reparto, sol_aleatoria)
print(type(sol_aleatoria))
print('REPARTO DE TOMAS POR DÍA: \n', sol_aleatoria)
print('GASTO ', DIA_2)# print actores/dia y coste total

Actor escogido para este día:  4
toma escogida:  1
TOMA:  1.0
toma escogida:  12
TOMA:  12.0
toma escogida:  6
TOMA:  6.0
toma escogida:  7
TOMA:  7.0
toma escogida:  20
TOMA:  20.0
toma escogida:  22
TOMA:  22.0
Actor escogido para este día:  7
toma escogida:  4
TOMA:  4.0
toma escogida:  3
TOMA:  3.0
toma escogida:  15
TOMA:  15.0
llega aquí
max_row:  11 actor_vecino:  1
llega aquí
Cambio de actor:  1
toma escogida:  11
TOMA:  11.0
toma escogida:  10
TOMA:  10.0
toma escogida:  25
TOMA:  25.0
Actor escogido para este día:  8
toma escogida:  5
TOMA:  5.0
toma escogida:  21
TOMA:  21.0
llega aquí
max_row:  8 actor_vecino:  6
Cambio de actor:  6
toma escogida:  8
TOMA:  8.0
toma escogida:  14
TOMA:  14.0
toma escogida:  29
TOMA:  29.0
toma escogida:  18
TOMA:  18.0

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  # This is added back by InteractiveShellApp.init_path()



Actor escogido para este día:  6
toma escogida:  24
TOMA:  24.0
llega aquí
max_row:  26 actor_vecino:  3
Cambio de actor:  3
toma escogida:  26
TOMA:  26.0
toma escogida:  2
TOMA:  2.0
toma escogida:  17
TOMA:  17.0
toma escogida:  19
TOMA:  19.0
toma escogida:  23
TOMA:  23.0
Actor escogido para este día:  9
llega aquí
max_row:  13 actor_vecino:  1
llega aquí
Cambio de actor:  1
toma escogida:  9
TOMA:  9.0
toma escogida:  13
TOMA:  13.0
toma escogida:  28
TOMA:  28.0
toma escogida:  30
TOMA:  30.0
llega aquí
max_row:  9 actor_vecino:  4
Cambio de actor:  4
toma escogida:  16
TOMA:  16.0
toma escogida:  27
TOMA:  27.0
Actor escogido para este día:  9
Condición STOP
Día  1  van  6.0  actores
Día  2  van  10.0  actores
Día  3  van  7.0  actores
Día  4  van  6.0  actores
Día  5  van  5.0  actores
[[1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 0. 0.]
 [1. 0. 1. 1. 1. 1. 0. 0. 1. 0.]
 [1. 1. 0. 1. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.

**Ejecutando una y otra vez, el menor valor que veo es GASTO = 34. Lo siguiente es aplicar un algoritmo de optimización para quedarnos con una aproximación del valor mínimo.**

### SEGUNDA SOLUCIÓN APLICANDO RAMIFICACIÓN Y PODA:
Solución por actores:

(*)Calcula la complejidad del algoritmo



### TERCERA SOLUCIÓN APLICANDO ALGÚN ALGORITMO HEURÍSTICO:
En concreto aplicaría una solución con algoritmos genéticos.

C

In [30]:
# Para ramificación y poda necesito la estructura de costes siguiente:

# Función de carga inicial de costes (sin tener en cuenta que los actores repiten toma!!!)
def carga_costes(reparto, nActores, limite):
  costes = np.zeros((30,limite))
  A,B = reparto.shape
  for i in range(A):
    for j in range(limite):
      costes[i,j] = nActores.iloc[i] # El coste de la toma i el día j es el total de actores de la toma
  return costes


limite = 6 # 6 días 
COSTES = carga_costes(rep,nActores,limite)
print(COSTES)

[[5. 5. 5. 5. 5. 5.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4.]
 [3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [4. 4. 4. 4. 4. 4.]
 [2. 2. 2. 2. 2. 2.]
 [4. 4. 4. 4. 4. 4.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3.]
 [2. 2. 2. 2. 2. 2.]]


In [70]:
# Sin considerar la posibilidad de que los actores realizan más de una toma al día:

def valor(S,COSTES): # Devuelve el coste de la tarea indicada mediante los valores del vector de entrada S, 
                     # para cada agente según la posición
  VALOR = 0
  for i in range(len(S)):
    VALOR += COSTES[int(S[i]),i]
  return VALOR


print(sol_aleatoria[0])
valor(sol_aleatoria[0],COSTES)

[ 1. 11.  6.  7. 20. 26.]


19.0

**Lo siguiente es calcular son los costes parciales para cada posible solución, en el caso de este problema, habría que mapear el reparto de cada toma con el resto elegido también para disminuir el coste en cada actor coincidente entre tomas, para recalcular los costes totales por toma antes de sacar el valor y coste inferior de cada solución.**


In [84]:
# Lo siguente sería estimar el coste inferior para soluciones parciales una vez se ha elegido

def CI(S,COSTES):
  VALOR = 0
  #Valores establecidos

  #Estimacion
  return VALOR

CI(sol_aleatoria[0],COSTES)

0

In [0]:
#Genera tantos hijos como como posibilidades haya para la siguiente elemento de la tupla
#
def crear_hijos(NODO, N):
  HIJOS = []
  for i in range(N):
    if i not in NODO:
      HIJOS.append({'s':NODO +(i,)    })
  return HIJOS

In [0]:
def ramificacion_y_poda(COSTES):
#Construccion iterativa de soluciones(arbol). En cada etapa asignamos un agente(ramas).
#Nodos del grafo  { s:(1,2),CI:3,CS:5  }
   #print(COSTES)
   DIMENSION = len(COSTES)  
   MEJOR_SOLUCION=tuple( i for i in range(len(COSTES)))
   CotaSup = valor(MEJOR_SOLUCION,COSTES)
   #print("Cota Superior:", CotaSup)

   NODOS=[]
   NODOS.append({'s':(), 'ci':CI((),COSTES)})

   iteracion = 0
   while( len(NODOS) > 0):
     iteracion +=1

     nodo_prometedor = [ min(NODOS, key=lambda x:x['ci']) ][0]['s']
     #print("Nodo prometedor:", nodo_prometedor)

     #Ramificacion
     #Se generan los hijos
     HIJOS =[ {'s':x['s'], 'ci':CI(x['s'], COSTES)   } for x in crear_hijos(nodo_prometedor, DIMENSION) ]

     #Revisamos la cota superior y nos quedamos con la mejor solucion si llegamos a una solucion final
     NODO_FINAL = [x for x in HIJOS if len(x['s']) == DIMENSION  ]
     if len(NODO_FINAL ) >0: 
       #print("\n********Soluciones:",  [x for x in HIJOS if len(x['s']) == DIMENSION  ] )
       if NODO_FINAL[0]['ci'] < CotaSup:
         CotaSup = NODO_FINAL[0]['ci']
         MEJOR_SOLUCION = NODO_FINAL
 
     #Poda
     HIJOS = [x for x in HIJOS if x['ci'] < CotaSup   ]

     #Añadimos los hijos 
     NODOS.extend(HIJOS) 

     #Eliminamos el nodo ramificado
     NODOS =  [  x for x in NODOS if x['s'] != nodo_prometedor    ]
   
   print("La solucion final es:" ,MEJOR_SOLUCION , " en " , iteracion , " iteraciones" , " para dimension: " ,DIMENSION  )
      

fuerza_bruta(COSTES)
print('RAMIFICACIÓN Y PODA:')
ramificacion_y_poda(COSTES)